name: SethsBlogBot

on:
  schedule:
    - cron: "0 12 * * *"   # هر روز ساعت 12:00 UTC (اگر می‌خواهی 11 بذاری 11 بنویس)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Cache HuggingFace & torch
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/huggingface
            ~/.cache/torch
          key: ${{ runner.os }}-hf-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py

      - name: Save last post link
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_post.txt || true
          git commit -m "Update last_post" || true
          git push || true
